config:
  target: 'http://someserver.com'
  phases:
    - duration: 180
      arrivalRate: 1
  defaults:
scenarios:
  - flow:
    - get:
        url: "/"
        headers: 
          x-Dynatrace: 'NA=Test.ListOrders;'

  