---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: "8-jdk-alpine"

inputs:
  - name: common-ci-repo
  - name: order-repo
  - name: version
outputs:
  - name: workspace

caches:
  - path: gradle
  - path: .m2

run:
  path: common-ci-repo/ci/tasks/build-artifact.sh
