---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: datianshi/cf-cli
    tag: "latest"

inputs:
- name: order-repo
- name: common-ci-repo

run:
  path: common-ci-repo/ci/tasks/cats.sh

params:
  MUSIC_URL:
