---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: datianshi/cf-cli
    tag: "latest"

inputs:
  - name: common-ci-repo  

run:
  path: music-repo/ci/tasks/cats.sh

params:
  MUSIC_URL:
