---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mvilliger/dynatrace-cli
    tag: "latest"

inputs:
- name: order-repo
- name: common-ci-repo

run:
  path: ./common-ci-repo/ci/tasks/init-dynatrace-task