---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mvilliger/dynatrace-cli
    tag: "latest"

inputs:
- name: music-repo

run:
  path: ./music-repo/ci/tasks/init-dynatrace-task