---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"


inputs:
- name: music-repo
- name: current-app-info

run:
  path: ./music-repo/ci/tasks/remove-routes