---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: "8-jdk-alpine"

inputs:
- name: order-repo
- name: common-ci-repo
caches:
  - path: gradle

run:
  path: ./common-ci-repo/ci/tasks/unit.sh
